export const houses = [
  {
    id: "1",
    imageURL: "/houses/1.png",
    price: 1169900000,
    name: "زمین مسکونی 378 متر شهرک انصاری",
    capacity: 10,
    sold: 8,
    tagNames: { tag1: "سند تک برگ", tag2: "مسکونی", tag3: "پنج طبقه مجاز" },
    tags: { tag1: true, tag2: true, tag3: true },
    categories: ["شخصی", "سند تک برگ"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند شخصی",
      Option3: "پلاک یک",
      Option4: "سند شخصی",
    },
    Options: { Option1: true, Option2: false,  Option3: false,  Option4: false },
    metrage: 378,
    bar: 13,
    karbari: "مسکونی",
    provience: "گیلان",
    city: "رودسر",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "2",
    imageURL: "/houses/2.png",
    price: 1800000000,
    name: "زمین چالوس زوات غرب",
    capacity: 8,
    sold: 4,
    tagNames: { tag1: "دریا", tag2: "مسکونی", tag3: "مشرف جنگل" },
    tags: { tag1: false, tag2: false, tag3: true },
    categories: ["دریا", "جنگل"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک دو",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 508,
    bar: 12,
    karbari: "مسکونی",
    provience: "مازندران",
    city: "چالوس",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "3",
    imageURL: "/houses/3.png",
    price: 320000000,
    name: "زمین تجاری",
    capacity: 12,
    sold: 11,
    tagNames: { tag1: "سند شورایی", tag2: "مسکونی", tag3: "مشرف جنگل" },
    tags: { tag1: true, tag2: false, tag3: true },
    categories: ["دریا", "جنگل"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک دو",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "4",
    imageURL: "/houses/4.png",
    price: 200000000,
    name: "زمین داخل بافت",
    capacity: 6,
    sold: 3,
    tagNames: { tag1: "سند شورایی", tag2: "مسکونی", tag3: "مشرف جنگل" },
    tags: { tag1: true, tag2: true, tag3: true },
    categories: ["سند شورایی", "جنگل"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: true, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "5",
    imageURL: "/houses/5.png",
    price: 280000000,
    name: "زمین مسکونی",
    capacity: 9,
    sold: 7,
    tagNames: { tag1: "سند شورایی", tag2: "مسکونی", tag3: "مشرف جنگل" },
    tags: { tag1: true, tag2: true, tag3: false },
    categories: ["مسکونی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "6",
    imageURL: "/houses/6.png",
    price: 300000000,
    name: "زمین تجاری مسکونی کمربندی نوشهر",
    capacity: 8,
    sold: 6,
    tagNames: { tag1: "سند شورایی", tag2: "مسکونی", tag3: "دریا" },
    tags: { tag1: true, tag2: false, tag3: true },
    categories: ["دریا"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },

  {
    id: "7",
    imageURL: "/houses/7.png",
    price: 220000000,
    name: "زمین مسکونی قابل تفکیک در منطقه چمستان",
    capacity: 7,
    sold: 4,
    tagNames: { tag1: "سند شورایی", tag2: "تجاری", tag3: "مشرف جنگل" },
    tags: { tag1: false, tag2: true, tag3: true },
    categories: ["تجاری"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "8",
    imageURL: "/houses/8.png",
    price: 350000000,
    name: "زمین مسکونی در سادات شهر",
    capacity: 10,
    sold: 9,
    tagNames: { tag1: "سند شورایی", tag2: "تجاری", tag3: "مشرف جنگل" },
    tags: { tag1: false, tag2: true, tag3: true },
    categories: ["تجاری"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "9",
    imageURL: "/houses/9.png",
    price: 270000000,
    name: "زمین در ارتفاعات رامسر",
    capacity: 8,
    sold: 5,
    tagNames: { tag1: "سند شورایی", tag2: "تجاری", tag3: "مشرف دریا" },
    tags: { tag1: false, tag2: true, tag3: true },
    categories: ["تجاری"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "10",

    imageURL: "/houses/10.png",
    price: 230000000,
  
    name: "زمین تجاری مسکونی",
    capacity: 6,
    sold: 3,
    tagNames: { tag1: "سند شورایی", tag2: "تجاری", tag3: "مشرف جنگل" },
    tags: { tag1: false, tag2: true, tag3: false },
    categories: ["تجاری"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: ["/houses/5.png", "/houses/6.png"],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
];
