export const houses = [
  {
    id: "1",
    imageURL: "/houses/wallpaperflare.com_wallpaper.jpg",
    price: 250000000,
    discount: 10,
    name: "ویلا مدرن",
    capacity: 10,
    sold: 8,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: true, tag2: false, tag3: true, tag4: false },
    categories: ["لوکس", "مدرن"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "2",
    imageURL: "/houses/wallpaperflare.com_wallpaper-2.jpg",
    price: 180000000,
    name: "کلبه دنج",
    capacity: 8,
    sold: 4,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: false, tag2: true, tag3: false, tag4: true },
    categories: ["مدرن"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "3",

    imageURL: "/houses/wallpaperflare.com_wallpaper-3.jpg",
    price: 320000000,
    name: "عمارت لوکس",
    capacity: 12,
    sold: 11,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: true, tag2: true, tag3: true, tag4: true },
    categories: ["لوکس"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "4",
    imageURL: "/houses/wallpaperflare.com_wallpaper-4.jpg",
    price: 200000000,
    discount: 15,
    name: "کلبه روستایی",
    capacity: 6,
    sold: 3,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: false, tag2: false, tag3: true, tag4: false },
    categories: ["روستایی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "5",
    imageURL: "/houses/wallpaperflare.com_wallpaper-5.jpg",
    price: 280000000,
    name: "اقامتگاه ساحلی",
    capacity: 9,
    sold: 7,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: true, tag2: false, tag3: false, tag4: true },
    categories: ["ساحلی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "6",
    imageURL: "/houses/wallpaperflare.com_wallpaper-6.jpg",
    price: 300000000,
    name: "کلبه کوهستانی",
    capacity: 8,
    sold: 6,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: false, tag2: true, tag3: true, tag4: false },
    categories: ["روستایی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },

  {
    id: "7",

    imageURL: "/houses/wallpaperflare.com_wallpaper-7.jpg",
    price: 220000000,
    discount: 20,
    name: "خانه روستایی",
    capacity: 7,
    sold: 4,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: true, tag2: false, tag3: false, tag4: false },
    categories: ["روستایی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "8",
    imageURL: "/houses/wallpaperflare.com_wallpaper-3.jpg",
    price: 350000000,
    name: "لوفت مدرن",
    capacity: 10,
    sold: 9,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: false, tag2: true, tag3: false, tag4: true },
    categories: ["مدرن"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "9",
    imageURL: "/houses/wallpaperflare.com_wallpaper-5.jpg",
    price: 270000000,
    name: "عمارت تاریخی",
    capacity: 8,
    sold: 5,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: true, tag2: true, tag3: true, tag4: false },
    categories: ["خارج شهر"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
  {
    id: "10",

    imageURL: "/houses/wallpaperflare.com_wallpaper-2.jpg",
    price: 230000000,
    discount: 10,
    name: "آپارتمان شهری",
    capacity: 6,
    sold: 3,
    tagNames: { tag1: "پروانه", tag2: "مستر", tag3: "پارکینگ", tag4: "شخصی" },
    tags: { tag1: false, tag2: false, tag3: false, tag4: true },
    categories: ["آپارتمانی"],
    latitude: 48.8584,
    longitude: 2.3549,
    galleryImages: [
      "/houses/wallpaperflare.com_wallpaper-3.jpg",
      "/houses/wallpaperflare.com_wallpaper-4.jpg",
    ],
    OptionsName: {
      Option1: "پلاک یک",
      Option2: "سند تک برگ",
      Option3: "مجوز ساخت",
      Option4: "باغ",
    },
    Options: { Option1: true, Option2: false, Option3: true, Option4: false },
    metrage: 2000,
    bar: 20,
    karbari: "کشاورزی",
    provience: "مازندران",
    city: "بابل",
    address: "جنب بانک کشاورزی",
  },
];
