export const houses = [
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper.jpg',
    price: 250000,
    discount: 10,
    name: 'Modern Villa',
    capacity: 10,
    sold: 8,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: true, tag2: false, tag3: true, tag4: false },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-2.jpg',
    price: 180000,
    name: 'Cozy Cottage',
    capacity: 8,
    sold: 4,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: false, tag2: true, tag3: false, tag4: true },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-3.jpg',
    price: 320000,
    name: 'Luxury Mansion',
    capacity: 12,
    sold: 11,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: true, tag2: true, tag3: true, tag4: true },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-4.jpg',
    price: 200000,
    discount: 15,
    name: 'Rustic Cabin',
    capacity: 6,
    sold: 3,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: false, tag2: false, tag3: true, tag4: false },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-5.jpg',
    price: 280000,
    name: 'Seaside Retreat',
    capacity: 9,
    sold: 7,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: true, tag2: false, tag3: false, tag4: true },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-6.jpg',
    price: 300000,
    name: 'Mountain Lodge',
    capacity: 8,
    sold: 6,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: false, tag2: true, tag3: true, tag4: false },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-7.jpg',
    price: 220000,
    discount: 20,
    name: 'Country Farmhouse',
    capacity: 7,
    sold: 4,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: true, tag2: false, tag3: false, tag4: false },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-3.jpg',
    price: 350000,
    name: 'Contemporary Loft',
    capacity: 10,
    sold: 9,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: false, tag2: true, tag3: false, tag4: true },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-5.jpg',
    price: 270000,
    name: 'Historic Manor',
    capacity: 8,
    sold: 5,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: true, tag2: true, tag3: true, tag4: false },
  },
  {
    imageURL: '/houses/wallpaperflare.com_wallpaper-2.jpg',
    price: 230000,
    discount: 10,
    name: 'Urban Apartment',
    capacity: 6,
    sold: 3,
    tagNames: { tag1: 'پروانه', tag2: 'مستر', tag3: 'پارکینگ', tag4: 'شخصی' },
    tags: { tag1: false, tag2: false, tag3: false, tag4: true },
  },
];
